function [ confStruct ] = BUILDCONFIGURATION( varargin )
%UNTITLED2 Summary of this function goes here
%   Detailed explanation goes here
    optionStrings =   { 'picWidth'...
                        'picHeight'...
                        'numSubPics'...
                        'debug'...
                        'useVJ'...
                        'saveFaces'...
                        'cascadeFile'...
                        'skipLBP'...
                        'svmOptions'...
                        'facesFolder'...
                        'VJminNeighbors' ...
                        'VJscaleFactor' ...
                        };
    
    defaultValues =  {  100 ...
                        100 ...
                        4 ...
                        false ...
                        false ...
                        false ...
                        'haarcascade_frontalface_alt2.xml' ...
                        false ...
                        '-t 0 -b 1' ...
                        'faces' ...
                        7 ...
                        1.1 ...
                        };

    confStruct = cell2struct(defaultValues,optionStrings,2);
    
    if rem(length(varargin),2) ~= 0
        fprintf('Wrong number of options, using default values\n');
        return;
    end
    
    for i=1:2:length(varargin)
        eval(['confStruct.' varargin{i} '=' varargin{i+1} ';']);
    end

end

